name: Auto Issue Assign

on:
  schedule:
    - cron: 0 */1 * * *
  issue_comment:
    types: [created]

jobs:
  assign:
    # If the acton was triggered by a new comment that starts with `/assign-to-me`
    # or a on a schedule
    if: >
     (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '!assign')) ||
      github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Assign the user or unassign stale assignments
        uses: takanome-dev/assign-to-me-action@v1.0.3
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          assigned_label: Is-Assigned # you can change this label if you wish
